# Generated by Django 4.1.3 on 2023-02-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bids_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_value',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
