# Generated by Django 4.1.3 on 2023-02-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bids_bid_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='listings',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
